export class CssClasses {
  public root = 'ka';
  public cell = 'ka-cell';
  public treeCell = 'ka-tree-cell';
  public treeCellEmptySpace = 'ka-tree-empty-space';
  public cellEditor: string = 'ka-cell-editor';
  public cellText = 'ka-cell-text';
  public groupCell = 'ka-group-cell';
  public groupSummaryRow = 'ka-group-summary-row'
  public detailsRow = 'ka-tr ka-details-row';
  public detailsCell = 'ka-details-cell';
  public groupRow = 'ka-tr ka-group-row';
  public groupSummaryCell = 'ka-cell ka-group-summary-cell';
  public groupPanel = 'ka-group-panel';
  public groupPanelCell = 'ka-group-panel-cell';
  public groupPanelCellRemove = 'ka-group-panel-cell-remove';
  public groupPanelText = 'ka-group-panel-text';
  public kaCellEditorValidationError = 'ka-cell-editor-validation-error';
  public row = 'ka-tr ka-row';
  public rowSelected = 'ka-row-selected';
  public tableWrapper = 'ka-table-wrapper';
  public table = 'ka-table';
  public tbody = 'ka-tbody';
  public tfoot = 'ka-tfoot';
  public thead = 'ka-thead';
  public theadBackground = 'ka-thead-background';
  public theadFixed = 'ka-thead-fixed';
  public theadCell = 'ka-thead-cell';
  public theadCellHeight = 'ka-thead-cell-height';
  public summaryCell = 'ka-summary-cell';
  public summaryRow = 'ka-summary-row';
  public theadCellContent = 'ka-thead-cell-content';
  public theadCellContentWrapper = 'ka-thead-cell-content-wrapper';
  public theadCellResize = 'ka-thead-cell-resize';
  public theadCellWrapper = 'ka-thead-cell-wrapper';
  public theadRow = 'ka-tr ka-thead-row';
  public draggedRow = 'ka-dragged-row';
  public dragOverRow = 'ka-drag-over-row';
  public draggedColumn = 'ka-dragged-column';
  public dragOverColumn = 'ka-drag-over-column';

  public paging = 'ka-paging';
  public pagingPages = 'ka-paging-pages';
  public pagingPageIndex = 'ka-paging-page-index';
  public pagingSize = 'ka-paging-size';
  public pagingSizes = 'ka-paging-sizes';
  public popupContent = 'ka-popup-content';
  public popupContentItem = 'ka-popup-content-item';

  public iconGroupArrowCollapsed = 'ka-icon ka-icon-group-arrow-collapsed';
  public iconGroupArrowExpanded = 'ka-icon ka-icon-group-arrow-expanded';
  public iconTreeArrowCollapsed = 'ka-icon ka-icon-tree-arrow-collapsed';
  public iconTreeArrowExpanded = 'ka-icon ka-icon-tree-arrow-expanded';
  public iconSort = 'ka-icon ka-icon-sort';
  public iconSortContent = 'ka-icon-sort-content';
  public iconSortArrowDown = 'ka-icon-sort-arrow-down';
  public iconSortArrowUp = 'ka-icon-sort-arrow-up';

  public checkbox = 'ka-input';
  public dateInput = 'ka-input';
  public numberInput = 'ka-input';
  public textInput = 'ka-input';
}
