// these data were generated by https://github.com/Marak/faker.js

export default [
    {
        company: { name: 'Windler, Conn' },
        hasLoyalProgram: true,
        id: 1,
        name: 'Giovani Pfannerstill',
        phoneNumber: '(796) 363-4261',
    },
    {
        company: { name: 'Feeney LLC' },
        hasLoyalProgram: false,
        id: 2,
        name: 'Arne Cummerata',
        phoneNumber: '(814) 734-6000',
    },
    {
        company: { name: 'Gleason - Beer' },
        hasLoyalProgram: false,
        id: 3,
        name: 'Viola Bashirian',
        phoneNumber: '(828) 300-0843',
    },
    {
        company: { name: 'Lebsack, Harvey' },
        hasLoyalProgram: true,
        id: 4,
        name: 'Michael Kemmer',
        phoneNumber: '(857) 146-2546',
    },
    {
        company: { name: 'Kuhn - Lubowitz' },
        hasLoyalProgram: false,
        id: 5,
        name: 'Janick Kohler',
        phoneNumber: '(236) 178-0050',
    },
];
